name: Rolling release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Build and upload binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Build binaries
        env:
          CGO_ENABLED: "0"
          GOFLAGS: "-trimpath -mod=readonly -modcacherw"
        run: |
          GOOS=linux   GOARCH=amd64 go build -o "magnetico-linux-amd64"       -ldflags "-s -w"
          GOOS=linux   GOARCH=arm64 go build -o "magnetico-linux-arm64"       -ldflags "-s -w"
          GOOS=darwin  GOARCH=amd64 go build -o "magnetico-darwin-amd64"      -ldflags "-s -w"
          GOOS=darwin  GOARCH=arm64 go build -o "magnetico-darwin-arm64"      -ldflags "-s -w"
          GOOS=windows GOARCH=amd64 go build -o "magnetico-windows-amd64.exe" -ldflags "-s -w"
          GOOS=windows GOARCH=arm64 go build -o "magnetico-windows-arm64.exe" -ldflags "-s -w"
      - name: Create release with binary assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete latest --cleanup-tag || true
          gh release create latest magnetico-* --latest
